{{- if .Values.rbac.enable -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "yc-preemptible-killer.fullname" . }}
  labels:
{{ include "yc-preemptible-killer.labels" . | indent 4 }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - delete
- apiGroups: [""] # "" indicates the core API group
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups: [""] # "" indicates the core API group
  resources:
  - pods/eviction
  verbs:
  - create
{{- end -}}
