{{- if .Values.secret.yandexServiceAccountKeyfileJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yc-preemptible-killer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "yc-preemptible-killer.labels" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.secret.valuesAreBase64Encoded }}
  service-account-key.json: {{.Values.secret.yandexServiceAccountKeyfileJson | toString}}
  {{- else }}
  service-account-key.json: {{.Values.secret.yandexServiceAccountKeyfileJson | toString | b64enc}}
  {{- end }}
{{- end }}
