{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "yc-preemptible-killer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "yc-preemptible-killer.labels" . | indent 4 }}
{{- end -}}
