apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: yc-preemptible-killer
  namespace: default
commonLabels:
  app: yc-preemptible-killer
resources:
- rbac.yaml
- service_account.yaml
- deployment.yaml
